# Generated by Django 5.1.15 on 2026-05-25 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('phrase', models.CharField(max_length=120, unique=True)),
                ('clue', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ensayoclinico',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='ensayoclinico',
            name='farmaco',
        ),
        migrations.RemoveField(
            model_name='ensayoclinico',
            name='pacientes',
        ),
        migrations.RemoveField(
            model_name='investigador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Farmaco',
        ),
        migrations.DeleteModel(
            name='EnsayoClinico',
        ),
        migrations.DeleteModel(
            name='Investigador',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
