# Generated by Django 5.1.15 on 2026-05-25 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_pregunta_remove_ensayoclinico_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='played_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
