# Generated by Django 5.1.15 on 2026-05-25 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_alter_partida_played_at_alter_pregunta_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaMultijugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(default='ESPERANDO', max_length=20)),
                ('preguntas_ids', models.CharField(default='', max_length=255)),
                ('panel_actual_index', models.IntegerField(default=0)),
                ('letras_usadas', models.TextField(default='')),
                ('valor_ruleta_actual', models.CharField(blank=True, max_length=20, null=True)),
                ('fase_turno', models.CharField(default='GIRAR', max_length=30)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_multijugador_creadas', to=settings.AUTH_USER_MODEL)),
                ('jugador_actual_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_multijugador_activos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JugadorPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_partida', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='examen.partidamultijugador')),
            ],
            options={
                'unique_together': {('partida', 'usuario')},
            },
        ),
    ]
