# Generated by Django 5.1.15 on 2026-05-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_partidamultijugador_jugadorpartida'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidamultijugador',
            name='ultimo_mensaje_suceso',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
